---
title: "flex dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

* need to put this line `rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")`
 in console so the dashboard knits like a dashboard bc if not and you just put it in the website, it will take on the formatting and visuals of a website and not the dashboard!!
 
 
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis" 
  )
```

### Chart C

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood,
    type = "bar", colors = "viridis"
  )
```

