---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
data("instacart") 


```

Click to go back to the [homepage](index.html).

Column {data-width=650}
-----------------------------------------------------------------------

### Reorders by Department

```{r}
instacart |> 
  drop_na(department) |> 
  filter(reordered == 1) |> 
  group_by(department, reordered) |> 
  summarize(reorder_amt = n()) |> 
  filter(reorder_amt > 5000) |> 
  plot_ly(x = ~department, 
          y = ~reorder_amt, 
          type = "bar", 
          color = ~department, 
          colors = "viridis"
          ) |> 
  layout(xaxis = list(categoryorder = "total descending"),
         xaxis = list(title = "Department"),
         yaxis = list(title = "Count of Reorders"),
         title = "Bar Chart Evaluating Which Departments Have the Most Reorders")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Ice Cream Orders by Day of Week


```{r}
instacart |> 
  filter(aisle == "ice cream ice") |> 
  mutate(order_dow = recode(order_dow,
                            `0` = "Sunday", `1` = "Monday", `2` = "Tuesday",
                            `3` = "Wednesday", `4` = "Thursday",
                            `5` = "Friday", `6` = "Saturday"),
         order_dow = factor(order_dow, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), ordered = TRUE)) |> 
  group_by(order_dow) |> 
  summarize(count = n()) |> 
  plot_ly(x = ~order_dow, 
          y = ~count,
          type = "scatter", 
          mode = "lines+markers", 
          line = list(shape = "spline")) |> 
  layout(
    title = "Trend of Ice Cream/Ice Aisle Purchases by Day of Week",
    xaxis = list(title = "Day of Week"),
    yaxis = list(title = "Number of Orders")
  )
```

### Random Sample of Add to Cart Order by Time Since Prior Order

```{r warning = FALSE}
instacart |> 
  drop_na(days_since_prior_order) |> 
  mutate(days_prior_order = cut(days_since_prior_order, breaks = c(0,5,10,15,20,25,30),
                        labels = c("0–5", "6–10", "11–15", "16–20", "21–25", "26–30"))) |> 
  sample_n(100) |> 
  plot_ly(
    x = ~days_prior_order, 
    y = ~add_to_cart_order,
    type = "box",
    color = ~days_prior_order,
    colors = "viridis"
  ) |> 
  layout(
    title = "Add-to-Cart Order by Time Since Prior Order in a Random Sample of 100",
    xaxis = list(title = "Days Since Prior Order"),
    yaxis = list(title = "Add to Cart Order"))
```

