---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

**EDUCATION**

**Columbia University Mailman School of Public Health** (Sept 2024 – May 2026)

*Master of Public Health in Epidemiology, Certificate in Applied Biostatistics and Data Science*

**Texas A&M University** (Aug 2020 – Dec 2023)

*Bachelor of Science in Public Health, Minors in Business and Psychology*	


**WORK EXPERIENCE**

**Stratis Group** (Sept 2025 – Present)

New York, New York

*Epidemiology Analyst*

* Supported epidemiology research initiatives across a range of therapeutic areas for biotech and pharma clients by conducting primary research and evaluating patient health outcomes, disease state, and burden

**Mailman School of Public Health - Department of Epidemiology**	(Sept 2025 – Present)

New York, New York

*Teaching Assistant*

* Provided administrative support for 2 courses (Principles of Epidemiology & Study Design) by updating Canvas page, sending announcements, troubleshooting technology, and facilitating communication between students and faculty

**Mallinckrodt Pharmaceuticals** (May 2025 – Aug 2025)

Bridgewater, New Jersey 

*Evidence Generation and Data Sciences Intern*

* Contributed to generating real world evidence by summarizing existing evidence, synthesizing current value strategy and tactic plan, conducting literature reviews, and preparing manuscripts and conference posters
* Collaborated cross-functionally with HEOR, Market Access, Scientific Communications, and Biostatistics teams 


**RESEARCH EXPERIENCE**

**Texas A&M University School of Public Health** (Jan 2024 – Jun 2024)

College Station, Texas

*Program Aide* 

* Consolidated and edited documents for IRB submissions in an Aging Asian American mental health project 
* Managed and developed participant surveys and led translation efforts between English/Chinese 


**Texas A&M University School of Public Health**  (Jun 2021 – Dec 2023)

College Station, Texas

*Student Research Assistant*

* Conducted over 300 secret shopper phone calls to collect data on a Consumer Access Project to evaluate healthcare accessibility 
* Engaged in indoor air quality monitoring in the Bryan-College Station area to analyze effects on asthma symptoms 
* Managed database, cleaned data, and analyzed using Microsoft Excel and Qualtrics across various projects 

	
**SKILLS**

Computer Skills: MS Office, SAS, RStudio 

Bilingual Chinese (Mandarin)




Click to go back to the [homepage](index.html).
